title: AI Storage Notes
description: AI Storage / KV Cache / GPU Data Path / S3 over RDMA

remote_theme: just-the-docs/just-the-docs@v0.12.0

plugins:
  - jekyll-remote-theme

url: "https://miauyle.github.io"
baseurl: "/ai-storage-notes"

search_enabled: true

aux_links:
  "GitHub":
    - "https://github.com/miauyle/ai-storage-notes"
